# Generated by Django 5.2.9 on 2026-01-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='link_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
