# Generated by Django 5.2.9 on 2026-01-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_resource_link_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['unit_number', 'type', 'title']},
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
