# Generated by Django 5.2.9 on 2026-01-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_alter_resource_options_resource_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['unit_number', 'type']},
        ),
    ]
